language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email: jiongsheng.lee@ncs.com.sg
    recipients:
      - email address>
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  
script:
  - ng build --prod --base-href https://burpie95.github.io/bitcoin-order-app/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development
